### ISSUE TITLE
03 Feedback

### ISSUE THREAD

**Issue by zanecochran** [Hannibell/CRT-420#3]
Processor - This is not on the list of approved processors. Please choose one from the project documentation list.

Output - What function does the NeoPixel serve? You didn't specify.

Power - Do not use the Adafruit PowerBoost 1000. Use the power management chip that I e-mailed you about instead.

**Comment by Hannibell** [comment]
I will be using 3 neopixels. Two neopixels will be mood indicators for Yilime, one inside each antennas. The last neopixel will be used as a battery indictor which will go from VBGYOR (100%-80%-60%-40%-20%-10%) .
